version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dronemetrics_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: dronemetrics
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # AICI E MODIFICAREA

volumes:
  db_data: